# Generated by Django 2.2.2 on 2019-07-15 11:38

import blog.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190715_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=blog.utils.get_uploaded_file_name),
        ),
    ]
